name: Deploy Release Docs

on:
  push:
    branches:
      - "release-*"

jobs:
  deploy:
    name: Trigger deployment
    if: ${{ github.repository_owner == 'catppuccin' }}

    permissions:
      actions: write

    runs-on: ubuntu-latest

    steps:
      - name: Dispatch website workflow
        env:
          GH_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
        run: |
          gh workflow run website.yml --repo "$REPOSITORY" --field deploy=true
